name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: pip install -U meson ninja
    - name: Configure Meson
      run: meson _build --buildtype=release --vsenv --prefix=C:\prefix-install
    - name: Build
      run: meson compile -C _build
    - name: Install
      run: meson install -C _build
    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: C:\prefix-install

